### ISSUE TITLE
 calling bitfinex.ticker(symbol='BTCUSD') fails

### ISSUE THREAD

**Issue by Leungfranklin** [jimako1989/bitfinexpy#4]
Error message as below. I am using python 3.5 in anaconda environment installed with tensorflow). is the error related to that?

Traceback (most recent call last):
  File "C:\Users\leung\Documents\GitHub\bitfinexpy\bitfinexpy.py", line 444, in <module>
    main()
  File "C:\Users\leung\Documents\GitHub\bitfinexpy\bitfinexpy.py", line 441, in main
    bitfinex.ticker(symbol='BTCUSD')
  File "C:\Users\leung\Documents\GitHub\bitfinexpy\bitfinexpy.py", line 23, in ticker
    return self.request(endpoint, auth=False, params=params)
  File "C:\Users\leung\Documents\GitHub\bitfinexpy\bitfinexpy.py", line 364, in request
    content = response.json()
  File "C:\Users\leung\Anaconda3\envs\tensorflow\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)

**Comment by tk42** [comment]
@Leungfranklin plz try fetch bugfix2 branch and execute it.

**Comment by Leungfranklin** [comment]
it works now, thank you for the prompt comment
